# replace default config

# multipass: true
# full: true

plugins:
  # - name
  #
  # or:
  # - name: false
  # - name: true
  #
  # or:
  # - name:
  #     param1: 1
  #     param2: 2

  - removeDoctype: true
  - removeXMLProcInst: true
  - removeComments: true
  - removeMetadata: true
  - removeXMLNS
  - removeEditorsNSData: true
  - cleanupAttrs: true
  - inlineStyles: true
  - minifyStyles: true
  - convertStyleToAttrs: true
  - cleanupIDs: true
  - prefixIds
  - removeRasterImages
  - removeUselessDefs: true
  - cleanupNumericValues: true
  - cleanupListOfValues
  - convertColors
  - removeUnknownsAndDefaults: true
  - removeNonInheritableGroupAttrs
  - removeUselessStrokeAndFill: true
  - removeViewBox
  - cleanupEnableBackground
  - removeHiddenElems: true
  - removeEmptyText: true
  - convertShapeToPath: true
  - convertEllipseToCircle
  - moveElemsAttrsToGroup: true
  - moveGroupAttrsToElems: true
  - collapseGroups: true
  - convertPathData: true
  - convertTransform: true
  - removeEmptyAttrs: true
  - removeEmptyContainers: true
  - mergePaths: true
  - removeUnusedNS: true
  - sortAttrs
  - sortDefsChildren
  - removeTitle: true
  - removeDesc: true
  - removeDimensions: true
  - removeAttrs:
      attrs: "(stroke|fill)"
  - removeAttributesBySelector
  - removeElementsByAttr
  - addClassesToSVGElement
  - removeStyleElement: true
  - removeScriptElement
  - addAttributesToSVGElement
  - removeOffCanvasPaths
  - reusePaths
# configure the indent (default 4 spaces) used by `--pretty` here:
#
# @see https://github.com/svg/svgo/blob/master/lib/svgo/js2svg.js#L6 for more config options
#
js2svg:
  pretty: true
#  indent: '  '
